server:
  port: 8090

spring:
  application:
    name: redpa-policy-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

info:
  app:
    name: RedPA Policy Service
    phase: "13"
