apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redpa.fullname" . }}-secrets
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secretEnv.DATABASE_URL | quote }}
  SECRET_KEY: {{ .Values.secretEnv.SECRET_KEY | quote }}
  API_KEY_PEPPER: {{ .Values.secretEnv.API_KEY_PEPPER | quote }}
