"""add document contents table

Revision ID: 5c21c59ce8e4
Revises: 172890f0158a
Create Date: 2026-07-29 19:02:49.378652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c21c59ce8e4'
down_revision: Union[str, Sequence[str], None] = '172890f0158a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_contents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_document_contents_document_id_documents', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_contents'))
    )
    op.create_index(op.f('ix_document_contents_document_id'), 'document_contents', ['document_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_contents_document_id'), table_name='document_contents')
    op.drop_table('document_contents')
    # ### end Alembic commands ###
