from __future__ import annotations

from enum import StrEnum


class ErrorCode(
    StrEnum,
):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    RATE_LIMITED = "RATE_LIMITED"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    WORKFLOW_ERROR = "WORKFLOW_ERROR"
    TOOL_EXECUTION_ERROR = "TOOL_EXECUTION_ERROR"
    REMOTE_AGENT_ERROR = "REMOTE_AGENT_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
